12:46:36 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
12:47:15 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
07:54:55 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
02:24:11 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
02:29:36 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
01:09:11 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:03:50 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:10:54 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:12:01 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:17:04 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:20:10 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:20:54 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:38:14 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
07:39:17 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
01:39:39 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
01:42:50 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
01:46:46 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
01:50:52 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
02:18:54 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:05:39 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:33:24 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:39:09 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:43:16 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:47:41 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
03:48:57 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
04:09:14 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
04:10:21 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
04:15:26 : ERROR [Conexion.py:24] Ocurrió una excepción al obtener la conexión: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
